=== Quicksilver666/jucy/eu.jucy.releng.languages/translation/lang.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Translation">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Plugin">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Trl">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="de" type="xs:string" />
                    <xs:element name="en" type="xs:string" />
                    <xs:element minOccurs="0" name="hu" type="xs:string" />
                    <xs:element minOccurs="0" name="it" type="xs:string" />
                    <xs:element minOccurs="0" name="ru" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Quicksilver666/jucy/eu.jucy.releng.languages/translation/lang.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Translation xmlns="http://jucy.eu/lang"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://jucy.eu/lang platform:/resource/eu.jucy.releng.languages/translation/lang.xsd" >
<Plugin id="eu.jucy.adlsearch" name="adl" langclass="eu.jucy.adlsearch.Lang">
<Trl id="ADL.ADLSearch">
<de>Automatische DateiListen Suche (ADL)</de>
<en>Automatic Directory Listing Search</en>
<it>Cartelle di destinazione</it>
<ru>ADL-поиск</ru>
</Trl>
<Trl id="ADL.Active">
<de>Aktiv</de>
<en>Active</en>
<it>Attiva</it>
<ru>Активный</ru>
</Trl>
<Trl id="ADL.Directory">
<de>Verzeichnis</de>
<en>Directory</en>
<it>Cartella</it>
<ru>Папка</ru>
</Trl>
<Trl id="ADL.DownloadMatches">
<de>Treffer Herunterladen</de>
<en>Download Matches</en>
<it>Scarica File trovati</it>
<ru>Скачать совпадения</ru>
</Trl>
<Trl id="ADL.Filename">
<de>Dateiname</de>
<en>Filename</en>
<it>Nome File</it>
<ru>Имя файла</ru>
</Trl>
<Trl id="ADL.FullPath">
<de>Ganzer Pfad</de>
<en>Full Path</en>
<it>Percorso</it>
<ru>Полный путь</ru>
</Trl>
<Trl id="ADL.MaxSize">
<de>Max Größe</de>
<en>Max Size</en>
<it>Dimensione massima</it>
<ru>Максимальный размер</ru>
</Trl>
<Trl id="ADL.MinSize">
<de>Min Größe</de>
<en>Min Size</en>
<it>Dimensione minima</it>
<ru>Минимальный размер</ru>
</Trl>
<Trl id="ADL.SearchString">
<de>Such Begriff</de>
<en>Search String</en>
<it>Cerca stringa</it>
<ru>Строка поиска</ru>
</Trl>
<Trl id="ADL.SearchType">
<de>Such Typ</de>
<en>Search Type</en>
<it>Tipo File</it>
<ru>Тип поиска</ru>
</Trl>
<Trl id="ADL.SizeType">
<de>Einheit</de>
<en>Size Type</en>
<it>Unità misura</it>
<ru>Размерность</ru>
</Trl>
<Trl id="ADL.TargetFolder">
<de>Ziel Verzeichnis</de>
<en>Target Folder</en>
<it>Cartella di destinazione</it>
<ru>Папка назначения</ru>
</Trl>
<Trl id="ADLSearch">
<de>ADL Suche</de>
<en>ADL Search</en>
<it>ADL Search</it>
<ru>ADL-поиск</ru>
</Trl>
</Plugin>
<Plugin id="eu.jucy.countries" name="countries" langclass="eu.jucy.countries.Lang">
<Trl id="Flags">
<de>Flaggen</de>
<en>Flags</en>
<it>Bandiere</it>
<ru>Флаги</ru>
</Trl>
<Trl id="IPFlagsDecoration">
<de>IP-Spalte - Flagen - Dekoration</de>
<en>IP-Column - Flags - Decoration</en>
<it>Colonna IP - Bandiere - Decorazioni</it>
<ru>Колонка с IP - Флаги - Оформление</ru>
</Trl>
<Trl id="Location">
<de>Ort</de>
<en>Location</en>
<it>Luogo</it>
<ru>Размещение</ru>
</Trl>
</Plugin>
<Plugin id="eu.jucy.gui" name="gui"  langclass="eu.jucy.gui.Lang">
<Trl id="ActionMen">
<de>Aktion</de>
<en>Action</en>
<hu>Mûködés</hu>
<it>Azioni</it>
<ru>Действия</ru>
</Trl>
<Trl id="ActiveModeSettings">
<de>Aktiver Modus Einstellungen</de>
<en>Active Mode Settings</en>
<hu>Aktív mód Beállításai</hu>
<it>Impostazioni Modalità Attiva</it>
<ru>Настройки активного режима</ru>
</Trl>
<Trl id="AddFolder">
<de>Neuer Ordner</de>
<en>Add folder</en>
<hu>Hozzáadás</hu>
<it>Aggiungi Cartella</it>
<ru>Добавить папку</ru>
</Trl>
<Trl id="AddSoundNotificationToChatroom">
<de>Füge Sound zu Nachrichten in Chaträumen hinzu</de>
<en>Add sound to message in chatroom</en>
<hu>Hangjelzés, ha üzenet érkezik a chatszobában</hu>
<it>Riproduci suono per messaggio in MainChat</it>
<ru>Добавить звуковое оповещение о сообщении в чате</ru>
</Trl>
<Trl id="AddSoundNotificationToPM">
<de>Füge Sound zu PMs hinzu </de>
<en>Add sound  to PM </en>
<hu>Hangjelzés, ha PÜ érkezik</hu>
<it>Riproduci suono per PM ricevuto</it>
<ru>Добавить звуковое оповещение о личном сообщении</ru>
</Trl>
<Trl id="AddSoundOnNickInMainchat">
<de>Füge Sound zu Nachrichten im Mainchat hinzu wenn der eigene Nick genannt wird</de>
<en>Add sound if own nick is named in mainchat</en>
<hu>Hangjelzés, ha valaki a mi becenevünket írja a fõablakban</hu>
<it>Riproduci suono se il tuo nick viene scritto in MainChat</it>
<ru>Добавить звуковое оповещение о хайлайте в чате</ru>
</Trl>
<Trl id="AddToFavorites">
<de>Hinzufügen zu Favoriten</de>
<en>Add To Favourites</en>
<hu>Kedvencekhez Adás</hu>
<it>Aggiungi ai preferiti</it>
<ru>Добавить в избранные</ru>
</Trl>
<Trl id="Added">
<de>Hinzugefügt</de>
<en>Added</en>
<hu>Hozzáadva</hu>
<it>Aggiunto</it>
<ru>Добавлено</ru>
</Trl>
<Trl id="AddedFileViaMagnet">
<de>Fügte %s via magnet link hinzu </de>
<en>Added %s via magnet link</en>
<it>Aggiunto %s con magnet link</it>
<ru>Добавлен %s по magnet-ссылке</ru>
</Trl>
<Trl id="Address">
<de>Addresse</de>
<en>Address</en>
<hu>Cím</hu>
<it>Indirizzo</it>
<ru>Адрес</ru>
</Trl>
<Trl id="Advanced">
<de>Erweitert</de>
<en>Advanced</en>
<hu>Haladó</hu>
<it>Avanzate</it>
<ru>Дополнительно</ru>
</Trl>
<Trl id="AdvancedFavHubProperties">
<de>Erweiterte FavHub Eigenschaften</de>
<en>Advanced FavHub properties</en>
<hu>Haladó Kedvenc Hubok beállításai</hu>
<it>Proprietà Avanzate Hub Preferiti</it>
<ru>Прочее...</ru>
</Trl>
<Trl id="All">
<de>Alle</de>
<en>All</en>
<hu>Mind</hu>
<it>Tutti</it>
<ru>Все</ru>
</Trl>
<Trl id="AllXUsersOffline">
<de>Alle %1$s User offline</de>
<en>All %1$s Users offline</en>
<hu>Minden %1$s felhasználó offline</hu>
<it>Tutti i %1$s User offline</it>
<ru>Никто из %1$s источников не в сети</ru>
</Trl>
<Trl id="AllowUsingUPnP">
<de>Nutze UPnP wenn nötig</de>
<en>Use UPnP if needed</en>
<hu>UPnP használata, ha szükséges</hu>
<it>Usa UPnP se necessario</it>
<ru>Использовать UPnP при необходимости</ru>
</Trl>
<Trl id="Appearance">
<de>Aussehen</de>
<en>Appearance</en>
<hu>Kinézet</hu>
<it>Stili e Colori</it>
<ru>Внешний вид</ru>
</Trl>
<Trl id="AreYouSureYouWantToCloseJucy">
<de>Willst du jucy beenden?</de>
<en>Are you sure you want to close jucy?</en>
<hu>Biztos, hogy bezárod a jucy-t??</hu>
<it>Sei sicuro di voler uscire da jucy?</it>
<ru>Вы точно хотите закрыть Jucy?</ru>
</Trl>
<Trl id="AskBeforeShutdown">
<de>Fragen vor dem Beenden</de>
<en>Ask before shutdown</en>
<hu>Rákérdezés, kilépés elõt</hu>
<it>Chiedi conferma prima di chiudere</it>
<ru>Спрашивать подтверждение при закрытии</ru>
</Trl>
<Trl id="AutoConnect">
<de>Automatisch verbinden</de>
<en>Auto connect</en>
<hu>Automatikus csatlakozás</hu>
<it>Connessione Automatica</it>
<ru>Автоподключение</ru>
</Trl>
<Trl id="AutoGrantSlot">
<de>Automatisch slot gewähren</de>
<en>Auto grant slot</en>
<hu>Automatikus slot biztosítása</hu>
<it>Slot Extra Automatico</it>
<ru>Автовыдача слота</ru>
</Trl>
<Trl id="AutomaticallyCheckForUpdates">
<de>Automatisch nach Updates suchen </de>
<en>Automatically check for updates</en>
<hu>Frissítések automatikus ellenõrzése</hu>
<it>Cerca aggiornamenti in automatico</it>
<ru>Автоматически проверять обновления</ru>
</Trl>
<Trl id="AutomaticallyFollowRedirects">
<de>Automatisch Umleitungen vom Hub Folgen</de>
<en>Automatically follow Redirects sent by Hub</en>
<it>Segui redirect proposti dall'hub</it>
<ru>Автоматически следовать перенапралению</ru>
</Trl>
<Trl id="AutomaticallySearchForAlternates">
<de>Automatisch nach alternativen Uploadern suchen</de>
<en>Automatically search for alternative Uploaders</en>
<hu>Alternatív feltöltõk automatikus keresése</hu>
<it>Cerca fonti alternative in automatico</it>
<ru>Автоматический поиск дополнительных источников</ru>
</Trl>
<Trl id="AverageSpeed">
<de>Durchschnittstempo: %s</de>
<en>Average Speed: %s</en>
<hu>Átlagos Sebesség: %s</hu>
<it>Velocità media: %s</it>
<ru>Средняя скорость: %s</ru>
</Trl>
<Trl id="Browse">
<de>Durchsuchen</de>
<en>Browse</en>
<hu>Tallózás</hu>
<it>Apri</it>
<ru>Обзор</ru>
</Trl>
<Trl id="BrowseFilelist">
<de>Durchsuche Dateiliste</de>
<en>Browse FileList</en>
<hu>Fájllista Tallózása</hu>
<it>Apri Lista File</it>
<ru>Просмотр списка файлов</ru>
</Trl>
<Trl id="CSNATDetected">
<de>NAT erkannt</de>
<en>NAT detected</en>
<hu>NAT detektálva</hu>
<it>Trovato NAT</it>
<ru>NAT обнаружен</ru>
</Trl>
<Trl id="CSNOTWORKING">
<de>FUNKTIONIERT NICHT</de>
<en>NOT WORKING</en>
<hu>NEM MÛKÖDIK</hu>
<it>INATTIVO</it>
<ru>НЕ РАБОТАЕТ</ru>
</Trl>
<Trl id="CSNoNATDetected">
<de>Direkte Verbindung</de>
<en>Direct Connection</en>
<hu>Közvetlen Csatlakozás</hu>
<it>Connessione Diretta (Attivo)</it>
<ru>Прямое соединение</ru>
</Trl>
<Trl id="CSPassiveMode">
<de>Passiv Modus (Eingeschränkte Suche, von anderen passiven kann nicht geladen werden)</de>
<en>Passive Mode (Restricted Search, no download from other passive users)</en>
<hu>Passzív Mód (Korlátozott Keresés, letöltés nem lehetséges más passzív felhasználótól)</hu>
<it>Modalità Passiva (Ricerca limitata, non scarichi da altri utenti passivi)</it>
<ru>Пассивный режим (поиск ограничен, нельзя скачивать с других пассивных юзеров)</ru>
</Trl>
<Trl id="CSToolTip">
<de>IP: %s 
%s
TCP status: %s
TCP+TLS status: %s
UDP status: %s
UPnP status: %s</de>
<en>IP: %s 
%s
TCP state: %s
TCP+TLS state: %s
UDP state: %s
UPnP state: %s</en>
<hu>IP: %s 
%s
TCP állapota: %s
TCP+TLS állapota: %s
UDP állapota: %s
UPnP állapota: %s</hu>
<it>IP: %s 
Stato TCP: %s
Stato UDP: %s
Stato UPnP: %s</it>
<ru>IP: %s.
%s
TCP: %s
TCP+TLS: %s
UDP: %s
UPnP: %s</ru>
</Trl>
<Trl id="CSUNKNOWN">
<de>UNBEKANNT</de>
<en>UNKNOWN</en>
<hu>ISMERETLEN</hu>
<it>SCONOSCIUTO</it>
<ru>НЕТ ДАННЫХ</ru>
</Trl>
<Trl id="CSWORKING">
<de>FUNKTIONIERT</de>
<en>WORKING</en>
<hu>MÛKÖDIK</hu>
<it>ATTIVO</it>
<ru>РАБОТАЕТ</ru>
</Trl>
<Trl id="ChatOnly">
<de>Nur Chat</de>
<en>ChatOnly</en>
<hu>Csak Chat</hu>
<it>Solo Chat</it>
<ru>Только чат</ru>
</Trl>
<Trl id="ChooseFolder">
<de>Wähle Ordner</de>
<en>Choose folder</en>
<hu>Válassz könyvtárat</hu>
<it>Scegli Cartella</it>
<ru>Выберите папку</ru>
</Trl>
<Trl id="Close">
<de>Schließen</de>
<en>Close</en>
<hu>Bezár</hu>
<it>Chiudi</it>
<ru>Закрыть</ru>
</Trl>
<Trl id="CloseAllPM">
<de>Schliesse PMs</de>
<en>Close PMs</en>
<hu>PÜ-k bezárása</hu>
<it>Chiudi tutti i PM</it>
<ru>Закрыть личку</ru>
</Trl>
<Trl id="CloseAllPMDescription">
<de>Schliest alle offenen PM Fenster</de>
<en>Closes all open PM windows</en>
<hu>Bezárja a összes PÜ ablakot</hu>
<it>Chiude tutti i PM aperti</it>
<ru>Закрывает все окна с личными сообщениями</ru>
</Trl>
<Trl id="CloseConnection">
<de>Schliesse Verbindung</de>
<en>Close connection</en>
